# Generated by Selenium IDE
import pytest
from model.group import Group
from fixture.application import Application

@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


  # Тестовый метод со значениями
def test_add_group(app):
    app.login(user_name="admin", password="secret")
    app.create_group(Group(name="r1", header="erer", footer="fgfg"))
    app.logout()

  # Тестовый метод без значений
def test_add_ampty_group(app):
    app.login(user_name="admin", password="secret")
    app.create_group(Group(name="", header="", footer=""))
    app.logout()



  
